---
- hosts: python
  become: true
  roles:
    - role: pkorobeinikov.apt-repository
      apt_repository_repositories:
        - repo: ppa:fkrull/deadsnakes

  tasks:
    - name: install python
      apt: name={{ item }} state=present
      with_items:
        - python3.5
        - python3.5-dev
        - python-pip
